steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'senslabs/datastore', '--network=cloudbuild', 'sens/datastore/generated/api/rest/main']
images:
  -   'gcr.io/$PROJECT_ID/datastore:$COMMIT_SHA'
